import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import MarkdownRenderer from '@/app/components/MarkdownRenderer'
import DownloadMarkdownButton from '@/app/components/DownloadMarkdownButton'
import { docPages, getBreadcrumbsForPath, sections } from '@/app/utils/navigation'
import { generatePageMetadata, getDocPageStructuredData } from '@/app/utils/metadata'
import mdContent from '@/public/data/md-content.json'

// Generate static params for all doc pages at build time
// Pages are statically generated by default (no dynamic functions used)
// Note: Glossary page has its own dedicated route, so we exclude it here
export async function generateStaticParams() {
  return docPages
    .filter((page) => page.path !== '/docs/glossary') // Exclude glossary (has dedicated route)
    .map((page) => {
      // Remove '/docs/' prefix and split into slug array
      const slug = page.path.replace('/docs/', '').split('/').filter(Boolean)
      return { slug }
    })
}

interface PageProps {
  params: Promise<{
    slug: string[]
  }>
}

// Generate metadata for SEO
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params
  // Handle case where slug might be undefined or empty
  if (!slug || !Array.isArray(slug) || slug.length === 0) {
    return {
      title: 'Page Not Found | BitcoinDev',
    }
  }

  const path = `/docs/${slug.join('/')}`
  const page = docPages.find(p => p.path === path)

  if (!page) {
    return {
      title: 'Page Not Found | BitcoinDev',
    }
  }

  // Get section description for overview pages
  const sectionInfo = sections[page.section]
  const description = sectionInfo
    ? sectionInfo.description
    : `${page.title} - Bitcoin development documentation`

  return generatePageMetadata({
    title: page.title,
    description,
    path,
  })
}

export default async function DocPage({ params }: PageProps) {
  const { slug } = await params
  // Handle case where slug might be undefined or empty
  if (!slug || !Array.isArray(slug) || slug.length === 0) {
    notFound()
  }

  // Reconstruct the path from slug segments
  const path = `/docs/${slug.join('/')}`

  // Look up content from md-content.json (same source as /api/download-md)
  const entry = (mdContent as Record<string, { content: string }>)[path]
  if (!entry?.content) {
    notFound()
  }

  const page = docPages.find((p) => p.path === path)
  const sectionInfo = page ? sections[page.section] : null
  const description = sectionInfo
    ? sectionInfo.description
    : page
      ? `${page.title} - Bitcoin development documentation`
      : ''
  const breadcrumbs = getBreadcrumbsForPath(path)
  const docStructuredData = getDocPageStructuredData(
    path,
    page?.title ?? '',
    description,
    breadcrumbs
  )

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: docStructuredData }}
      />
      <div className="relative">
        <div className="absolute top-0 right-0 z-10 hidden md:block">
          <DownloadMarkdownButton />
        </div>
        <MarkdownRenderer content={entry.content} />
        <div className="absolute -bottom-8 right-0 z-10 hidden md:block">
          <DownloadMarkdownButton />
        </div>
      </div>
    </>
  )
}
