import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import MarkdownRenderer from '@/app/components/MarkdownRenderer'
import { readMarkdown } from '@/app/utils/readMarkdown'
import { pathToMdFile, docPages, sections } from '@/app/utils/navigation'
import { generatePageMetadata } from '@/app/utils/metadata'

// Generate static params for all doc pages at build time
// Pages are statically generated by default (no dynamic functions used)
// Note: Glossary page has its own dedicated route, so we exclude it here
export async function generateStaticParams() {
  return docPages
    .filter((page) => page.path !== '/docs/glossary') // Exclude glossary (has dedicated route)
    .map((page) => {
      // Remove '/docs/' prefix and split into slug array
      const slug = page.path.replace('/docs/', '').split('/').filter(Boolean)
      return { slug }
    })
}

interface PageProps {
  params: Promise<{
    slug: string[]
  }>
}

// Generate metadata for SEO
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params
  // Handle case where slug might be undefined or empty
  if (!slug || !Array.isArray(slug) || slug.length === 0) {
    return {
      title: 'Page Not Found | B++',
    }
  }

  const path = `/docs/${slug.join('/')}`
  const page = docPages.find(p => p.path === path)

  if (!page) {
    return {
      title: 'Page Not Found | B++',
    }
  }

  // Get section description for overview pages
  const sectionInfo = sections[page.section]
  const description = sectionInfo
    ? sectionInfo.description
    : `${page.title} - Bitcoin development documentation`

  return generatePageMetadata({
    title: page.title,
    description,
    path,
  })
}

export default async function DocPage({ params }: PageProps) {
  const { slug } = await params
  // Handle case where slug might be undefined or empty
  if (!slug || !Array.isArray(slug) || slug.length === 0) {
    notFound()
  }

  // Reconstruct the path from slug segments
  const path = `/docs/${slug.join('/')}`

  // Look up the markdown file for this path
  const mdFile = pathToMdFile[path]

  // If path doesn't exist in our mapping, return 404
  if (!mdFile) {
    notFound()
  }

  // Read and render the markdown content
  try {
    const content = await readMarkdown(mdFile)

    return (
      <div className="max-w-4xl">
        <MarkdownRenderer content={content} />
      </div>
    )
  } catch (error) {
    // Log error in production for debugging
    console.error(`Error reading markdown file ${mdFile}:`, error)
    notFound()
  }
}
